### ISSUE TITLE
how the money is given to the end beneficiary ?

### ISSUE THREAD

**Issue by joicemjoseph** [digitatorin/auto-research#10]
- directly to driver
- prepaid in the app

**Comment by arunk** [comment]
lets keep this simple again for now. the app can merely connect the user and the auto driver. the user has to pay the auto driver their fare. maybe there is a model in which the user pays the driver something extra like uber and ola does right now? will that be enough of an incentive for drivers to use this app, as opposed to ola/uber who pays them an additional 20-30, will have to be seen.
