### ISSUE TITLE
how we can ensure the behaviour of driver is good.

### ISSUE THREAD

**Issue by joicemjoseph** [digitatorin/auto-research#11]
in many cities, auto drivers are demanding the money as they like. not as regulated by authorities. And the threat of bad behaviour will also affect our service.
how to manage similar possibility of [Uber Delhi](www.bbc.co.uk/news/world-asia-india-34707254) controversy

**Comment by arunk** [comment]
i was imagining a rating service. auto drivers can rate passengers, and passengers can rate auto drivers. if an auto driver gets enough bad ratings for demanding excess fare, they lose the risk of getting future customers. similarly if a passenger behave rudely towards enough auto drivers, then they might not get people willing to take them in their auto.
