### ISSUE TITLE
How to handle argument on fare between auto driver and the end user ?

### ISSUE THREAD

**Issue by joicemjoseph** [digitatorin/auto-research#12]
if the fare is fixed before the trip, it reduces the ability of driver
to argue about the fare.
if he think like the ride worth than what he accepted as fare, he should
be arguing. right ?
how can handle such cases?

**Comment by arunk** [comment]
lets keep it simple for now. forget fixed fare, since it will be hard to know beforehand the route that will be taken, how much delay or waiting there might be etc. at best the phone app can provide some kind of distance checker for the passenger to ensure that the meter that the auto has is working properly

**Comment by joicemjoseph** [comment]
@rashivkp I am considering consulting the option what we had discussed AFK @ kenichira. 
we can make a table of payment related details from the cooperative if that is a village. ( If there is a commonly agreed price chart, we can use that. ) If the autos in the coop is running without a price chart, we can use the meter or manually calculating the money required to be payed.
But we need to decide weather it is to be used in our mvp. please comment on #21 about billing policy.
and later we can do a poll in loomio if needed.

**Comment by rashivkp** [comment]
until we implement the payment system/wallet we should rely on driver. 

IMHO, price-chart won't be practical. we already know the minimum charge, km charge, returning fare, and so.. we can show that to user. clients won't accept different standard of pricing for a specific area. do they ? if it is so, is it fare ? it depends on the drivers.

**Comment by joicemjoseph** [comment]
There comes the problem, I think. There is a possibility of collision between driver and user. that will be very tough for our platform. 
The fraction of price, shortage of coins etc will affect our system. rounding the amount to ceil might raise more than that of the price chart. so these are the problems. If a user is travelling through a village or local area, it is very common and usual, that they are using a price chart; everybody knows that. we are showing them the amount before initiating ride, so that wont be a problem. Otherwise, I think, we should drop the money related modules from MVP. 
@arunk what you think ?

**Comment by rashivkp** [comment]
actually I meant that. ie no money transactions in MVP

**Comment by joicemjoseph** [comment]
@rashivkp in other words, you mean not showing any rate details in client search.

**Comment by rashivkp** [comment]
if we did show a specific rate, it will probably be a cause to an argument unless the driver accepted that rate !! right ?

**Comment by joicemjoseph** [comment]
the cooperative society, the auto driver is associated with is providing the fixed rates. So, there is no problem with or issue with driver. We are just service providers. 
I hope there is no other problems related to the issue. @arunk @rashivkp If you think there is no other problems associated with this, please make comments to wind up. then we can close this issue and mark decided.

**Comment by arunk** [comment]
yes @joicemjoseph as per our discussions yesterday, perhaps we can allow the service to provide a rate card if the cooperative/organization running the service chooses to publish one.

**Comment by joicemjoseph** [comment]
And also we are constructing a market place, which makes them possible to bargain, right ?
