### ISSUE TITLE
using Parse as application backend

### ISSUE THREAD

**Issue by joicemjoseph** [digitatorin/auto-research#20]
Parse is known for its easiness, quickness etc in building applications. The SaaS platform has been discontinued after facebook's acquisition. They had open sourced their platform and we can take advantage of that. with a minor update, we can make use that in our application. It is basically depending on a no sql database. So I think there are geo datatype available.

**Comment by joicemjoseph** [comment]
https://github.com/ParsePlatform/parse-server

**Comment by joicemjoseph** [comment]
@arunk , @rashivkp what about this ?
https://github.com/swagger-api
http://swagger.io/

**Comment by rashivkp** [comment]
for now, at least for the beginning I prefer to stick to the parts we already familiar with. so, we can think about every new, innovating and better technologies that we are not familiar, in a later stage after the first prototype. what you think ?

**Comment by joicemjoseph** [comment]
It is a considerable option. Thats why I mentioned that. Almost every MVP are using Parse. It is quit easy. But the problem is more logic come to the android application.
