### ISSUE TITLE
Minimum Viable Product

### ISSUE THREAD

**Issue by joicemjoseph** [digitatorin/auto-research#21]
our first release will be MVP. So, what is its strategy ?
How we are going to design that ? How its functionality going to be ?

**Comment by arunk** [comment]
The same as Ola/Uber/X-service app. Lets try and build it as generic and simple as possible?

**Comment by joicemjoseph** [comment]
I had listed out something which came to mind, it is as  follows.
There should be

### In The user application
- A **rating** system for drivers
- Mechanism for **Abuse Reporting**.
- Exclude auto from ride search.
- Save the auto driver contact details for offline usage.
- show **auto rickshaws nearby** by default.
- Favourite rides - this can be either quick ride location or favourite auto driver.
- A list of autos whom they had rated.
  #22, we can discuss algorithm for the list ranking and prioritization. 
  #23, we can discuss the search filters for user application.
