### ISSUE TITLE
Business and earning model

### ISSUE THREAD

**Issue by joicemjoseph** [digitatorin/auto-research#3]
It is very crucial to have a business model for an open source project, especially for co-operative societies. 
Especially this project aims the growth and wealth of the common people who lend auto for daily, having a business model or earning model will be more and more complicated.

**Comment by arunk** [comment]
currently this project needs a way to sustain itself and run. the major cost of this is the development cost. as long as we can continue to develop this service and even if it works to help just one union of a 20 auto drivers in wayanad or bangalore, it's worth doing in my opinion. let's just cover our running expenses first, then we can worry about business plans and earning models.
